Use is_alive in favour of isAlive for Python 3.9 compatibility.
ARMmbed/mbed-os-tools pull request #248
Opened 2020-11-17 05:57 UTC by tirkarthi

### Description

Use `is_alive` in favour of `isAlive` for Python 3.9 compatibility. `is_alive` is present in both Python 2 and 3. Fixes #247 

### Pull request type

    [x] Fix
    [ ] Refactor
    [ ] Target update
    [ ] Functionality change
    [ ] Docs update
    [ ] Test update
    [ ] Breaking change

### Reviewers

2021-02-09 16:43 UTC, LDong-Arm commented
Hello, is there any chance of getting this merged? It works for Python 3.6 and above. Python 3.5 and below are not actively supported anymore: https://www.python.org/downloads/ and Python 2.x reached the end of support in 2020: https://www.python.org/doc/sunset-python-2/

2021-02-10 11:56 UTC, Patater commented
@LDong-Arm Sorry, no. In this repo, we'd need a solution that still worked for 2.7 because these are our legacy Mbed tools. The new Mbed tools don't have this restriction. As for when we start shipping a Greentea that doesn't support Python 2, we don't know yet, but it'll be from a standalone Greentea repo (not this repo).

2021-02-10 12:18 UTC, LDong-Arm commented
> @LDong-Arm Sorry, no. In this repo, we'd need a solution that still worked for 2.7 because these are our legacy Mbed tools. The new Mbed tools don't have this restriction. As for when we start shipping a Greentea that doesn't support Python 2, we don't know yet, but it'll be from a standalone Greentea repo (not this repo).

Fair enough, it makes sense for legacy tools to prioritise backward compatibility.

2021-02-10 13:59 UTC, Patater commented
> > @LDong-Arm Sorry, no. In this repo, we'd need a solution that still worked for 2.7 because these are our legacy Mbed tools. The new Mbed tools don't have this restriction. As for when we start shipping a Greentea that doesn't support Python 2, we don't know yet, but it'll be from a standalone Greentea repo (not this repo).
> 
> Fair enough, it makes sense for legacy tools to prioritise backward compatibility.

If we can add the support here without breaking 2.7 and 3.5, that'd work.

2021-02-10 14:37 UTC, rwalton-arm commented
You could probably check if the attribute exists first.

```
if hasattr(t, "isAlive"):
    t.isAlive()
else:
    t.is_alive()
```

2021-02-10 14:54 UTC, LDong-Arm commented
Good suggestion. And we could check the "preferred" (up to date one) first which is `is_alive`.

2021-02-10 15:01 UTC, tirkarthi commented
is_alive is present in both python  2 and 3.

2021-03-30 16:20 UTC, harmut01 commented
@tirkarthi, @LDong-Arm what is the status on this PR? I'm still unable to run greentea tests with python 3.9.

2021-03-30 16:31 UTC, LDong-Arm commented
> @tirkarthi, @LDong-Arm what is the status on this PR? I'm still unable to run greentea tests with python 3.9.

I locally make the change on my machine, but it'd be really good to have the fix in. Python 3.9 has been available for a while now.

@tirkarthi has a good point - from the Python [documentation](https://docs.python.org/2.7/library/threading.html), even the legacy Python 2.7 and 3.5 should support `is_alive()`. @Patater @rwalton-arm Is it possible our CI does not have the latest path releases of both Python versions?

2021-06-11 12:34 UTC, LDong-Arm commented
I think we should try to give this PR a push. Still facing the error every time my python packages are updated.

2021-06-11 12:35 UTC, LDong-Arm commented
Could do it in https://github.com/ARMmbed/greentea once that's available for use

2021-09-02 14:51 UTC, rwalton-arm commented
I strongly suggest we merge this PR. We need to continue supporting these tools and they are currently completely broken on python 3.9>. 

One of the reasons CI was failing for python 3.5 was because of an issue with "prettytable" (since fixed, in fact we dropped 3.5 from the CI matrix completely in https://github.com/ARMmbed/mbed-os-tools/commit/3c6400e29388b5a884dfbeaa7df354abec75c020). 

@tirkarthi Sorry for the extremely long delay in reviewing this PR, but could you please rebase on the latest master so we can re-run the CI (and finally get this fix merged). Thanks!

2021-09-02 15:41 UTC, tirkarthi commented
@rwalton-arm Sure, updated my PR with master.

2021-09-02 16:42 UTC, LDong-Arm approved these changes

2021-09-03 09:05 UTC, rwalton-arm requested changes
Thanks @tirkarthi - sorry to be a pain but could you rebase instead of merging the master branch? We don't usually accept merge commits in PRs. Thanks!

2021-09-03 10:01 UTC, tirkarthi commented
@rwalton-arm Ok, I just used github U for updating branch which uses merge. I reverted my merge and did a rebase now.

2021-09-03 10:25 UTC, rwalton-arm approved these changes

2021-09-03 10:25 UTC, merged