ST board Id: Alignment with pyOCD v0.30.3
ARMmbed/mbed-os-tools pull request #262
Opened 2021-06-09 14:17 UTC by jeromecoutant

### Description

Alignment with pyOCD v0.30.3

Same action done on pyOCD: https://github.com/pyocd/pyOCD/pull/1166

### Pull request type

    [x] Fix
    [ ] Refactor
    [ ] Target update
    [ ] Functionality change
    [ ] Docs update
    [ ] Test update
    [ ] Breaking change

### Reviewers

2021-06-15 08:24 UTC, jeromecoutant commented
@MarceloSalazar

2021-06-15 14:35 UTC, MarceloSalazar commented on src/mbed_os_tools/detect/platform_database.py
> +        u"0853": u"NUCLEO_F031K8",
This seems a typo. It should be `NUCLEO_F301K8`

2021-06-15 14:36 UTC, MarceloSalazar requested changes
Please fix the target name

2021-06-16 20:10 UTC, MarceloSalazar commented
@Patater can you please merge when you have chance?

2021-06-24 08:52 UTC, jeromecoutant commented
ping

2021-07-15 13:31 UTC, MarceloSalazar commented
@Patater please review and merge - thanks

2021-07-21 14:35 UTC, merged